---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: taxideployment
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: taxiapp
 template:
  metadata:
   name: taxiapppod
   labels:
     app: taxiapp	 
  spec: 
    containers:
    - name: taxiappcontainer
      image: prasadnaidu123/prasad
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: taxiappsvc
spec:
  type: NodePort
  selector:
   app: taxiapp
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30736
...
